service: redshift-sync
frameworkVersion: ">=1.8.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  memorySize: 128
  timeout: 30
  environment:
    PGUSER: ${opt:pg-username}
    PGHOST: ${opt:pg-host}
    PGPASSWORD: ${opt:pg-password}
    PGDATABASE: ${opt:pg-db}
    PGPORT: 5439
    SLACK_WEBHOOK: ${opt:slack-webhook}

functions:
  check:
    handler: functions/check.handler
    events:
      - schedule: rate(1 hour)
